resolver: lts-18.28

# Local packages, usually specified by relative directory name
packages:
- '.'

extra-deps: 
- unbound-generics-0.4.1@sha256:5020e8397dad610846cbd5bdc855e20edf9b9cb74f93f6c09488bba21118c409,5485


flags: {}

extra-package-dbs: []

