resolver: lts-18.28

# Local packages, usually specified by relative directory name
packages:
- '.'

extra-deps:
- git: git@github.com:lambdageek/unbound-generics.git
  commit: 54096156b06dda2fcc523939de6da64b43737ea4


flags: {}

extra-package-dbs: []

